INSERT INTO matt_air.location VALUES
(1,"Manchester Airport","Manchester","England",0),
(2,"Heathrow","London","England",0),
(3,"London City Airport","London","England",0),
(4,"Gatwick Airport","London","England",0),
(5,"Luton Airport","London","England",0),
(6,"London Stansted Airport","London","England",0),
(7,"London Southend Airport","London","England",0),
(8,"Birmingham Airport","Birmingham","England",0),
(9,"Bristol Airport","Bristol","England",0),
(10,"Newcastle Airport","Newcastle","England",0),
(11,"Liverpool John Lennon Airport","Liverpool","England",0),
(12,"Cardiff Airport","Cardiff","Wales",0),
(13,"Edinburgh Airport","Edinburgh","Scotland",0),
(14,"Glasgow Airport","Glasgow","Scotland",0),
(15,"Belfast International Airport","Belfast","Northern Ireland",0),
(16,"Dubin Airport","Dublin","Republic of Ireland",0);